# Site settings
author: Kevin Xirum
title: 1st Blog
header-img: img/home-bg.png
email: kevinmenjivar66@gmail.com
copyright_name: Kevin Xirum
description: > # this means to ignore newlines until "baseurl:"
  About me
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  KevinXirum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
